### ISSUE TITLE
`FLT.FreyPackage.of_not_FermatLastTheorem`

### ISSUE THREAD

**Issue by kbuzzard** [ImperialCollegeLondon/FLT#19]
The issue here is a very tedious one. I write down an algorithm to do the manipulations of a counterexample explained in the LaTeX file, and now I am faced with the prospect of having to verify that the algorithm is correct. This whole thing could probably be tidied up very well by someone who knows something about computer science.

**Comment by nkzarrabi** [comment]
I saw there is a pull request open for this. Is the issue assigned to anyone? I would be interested in seeing how I can contribute

**Comment by kbuzzard** [comment]
Yeah this issue looks like it's done now. I've not opened issues for the things people are currently working on -- they are being documented on the Lean Zulip in threads like this https://leanprover.zulipchat.com/#narrow/stream/416277-FLT/topic/Outstanding.20Tasks.2C.20V2/near/437156084
