### ISSUE TITLE
The integral closure of a Dedekind domain in a finite separable extension is finite

### ISSUE THREAD

**Issue by kbuzzard** [ImperialCollegeLondon/FLT#202]
Is it true that if A is a Dedekind domain with field of fractions K, and if L/K is a finite separable extension, then the integral closure B of A in L is a finite A-module? I'm assuming so but was reluctant to add it as an assumption if it was not true in this generality. This is

```lean
example : Module.Finite A B := by sorry -- I assume this is correct
```

in `FLT.DedekindDomain.FiniteAdeleRing.BaseChange` .

**Comment by 4hma4d** [comment]
It seems to be true by [this](https://stacks.math.columbia.edu/tag/032L)

**Comment by 4hma4d** [comment]
claim

**Comment by alreadydone** [comment]
I also found a [reference to Milne](https://mathoverflow.net/questions/378941/finiteness-of-the-integral-closure-of-an-integral-domain-in-its-field-of-fractio), and a [reference to a counterexample](https://mathoverflow.net/a/21348/3332) in the inseparable case.

**Comment by Ruben-VandeVelde** [comment]
This is done in 2473f61ed74945390df2608d76f8095b8a7457c5

**Comment by kbuzzard** [comment]
Thanks!
