### ISSUE TITLE
Definition of the K-algebra map prod_v K_v -> prod_w L_w

### ISSUE THREAD

**Issue by kbuzzard** [ImperialCollegeLondon/FLT#206]
Previous work in the file `FLT.DedekindDomain.FiniteAdeleRing.BaseChange` gives maps K_v -> L_w on completions of fields of fractions of Dedekind domains at maximal ideals. The product of such maps should give us a K-algebra homomorphism from prod_v K_v to prod_w L_w. I've mis-stated this claim in the declaration `ProdAdicCompletions.baseChange` because I've acidentally made it a K-module map rather than a K-algebra map. The sorries in the latter declaration should be straightforward but what really should be done is that my error should be fixed and this declaration should be beefed up to a K-algebra map; this should also hopefully be easy for someone who knows the algebra API.

**Comment by maddycrim** [comment]
claim
