### ISSUE TITLE
The L-algebra map L tensor K_v -> prod_{w|v} L_w is continuous

### ISSUE THREAD

**Issue by kbuzzard** [ImperialCollegeLondon/FLT#237]
The K-algebra map K_v -> prod_{w|v} L_w is continuous, and L/K is finite, and L tensor K_v has the module topology, so this issue is just a case of figuring out why tensoring with L preserves continuity.

**Comment by erdOne** [comment]
This follows immediately from https://github.com/leanprover-community/mathlib4/pull/19515 I think

**Comment by kbuzzard** [comment]
This is in FLT now. Do you want to try your luck @erdOne ?
