### ISSUE TITLE
if x in prod_v K_v then x is a finite adele iff l (x) x in prod_w L_w is a finite adele

### ISSUE THREAD

**Issue by kbuzzard** [ImperialCollegeLondon/FLT#241]
We assume that 1 (x) x is a finite adele iff x is, so this is easy; one way is "set l=1" and the other way is "product of a finite adele of L and an element of L is a finite adele of L".

**Comment by WilliamCoram** [comment]
claim

**Comment by WilliamCoram** [comment]
propose #282
