### ISSUE TITLE
The rationals are discrete in the adeles of the rationals

### ISSUE THREAD

**Issue by kbuzzard** [ImperialCollegeLondon/FLT#256]
Assuming `Rat.AdeleRing.zero_discrete`, i.e. that there's some open U in A_Q whose intersection with Q is {0}, deduce that for all rationals q there's an open V in A_Q whose intersection with Q is {q}. Proof: V=U+q.

The sorry is in `NumberField/AdeleRing.lean`

**Comment by jcommelin** [comment]
claim

**Comment by jcommelin** [comment]
closed by #266
